version: '3.9'

services:
  openaibot:
    image: aiastia/blipserver:main
    command: python3 app.py
    volumes:
      - ./:/app
    networks:
      - app-tier
  

networks:
  app-tier:
    driver: bridge
